
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '80B3DCD07D1A0658E32B7EDF633EF855'
    
_lr_action_items = {'STRING':([0,9,11,13,15,20,],[2,13,16,-9,19,-7,]),'-':([2,3,14,16,],[9,10,18,9,]),'DATE':([0,],[1,]),'INTEGER':([0,5,10,17,18,21,],[3,12,14,20,21,-8,]),':':([12,],[17,]),'$end':([0,1,2,4,5,6,7,8,13,19,21,],[-11,-4,-6,0,-3,-5,-2,-1,-9,-10,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[4,]),'time':([5,],[11,]),'date':([0,],[5,]),'offense':([0,11,],[6,15,]),'data':([0,],[7,]),'empty':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> empty','start',1,'p_start','PLYmpstat.py',56),
  ('start -> data','start',1,'p_start','PLYmpstat.py',57),
  ('start -> date','start',1,'p_start','PLYmpstat.py',58),
  ('start -> DATE','start',1,'p_start','PLYmpstat.py',59),
  ('start -> offense','start',1,'p_start','PLYmpstat.py',60),
  ('start -> STRING','start',1,'p_start','PLYmpstat.py',61),
  ('time -> INTEGER : INTEGER','time',3,'p_time','PLYmpstat.py',66),
  ('date -> INTEGER - INTEGER - INTEGER','date',5,'p_date','PLYmpstat.py',70),
  ('offense -> STRING - STRING','offense',3,'p_offense','PLYmpstat.py',74),
  ('data -> date time offense STRING','data',4,'p_data','PLYmpstat.py',79),
  ('empty -> <empty>','empty',0,'p_empty','PLYmpstat.py',84),
]
